# Generated by Django 3.0.6 on 2020-05-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='created',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
