# Generated by Django 3.0.6 on 2020-05-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_pages_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='created',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
